### ISSUE TITLE
t5gec model trained on CLang8

### ISSUE THREAD

**Issue by antct** [zhangying9128/BTR#1]
Hi, thanks for your nice work~
Is there any checkpoint available of the model finetuned on the trained dataset CLang 8? 
I wanna to generate some candidates by myself. Thanks~

**Comment by zhangying9128** [comment]
Hi, @antct thank you for your interesting.
Please check our readme file, we offered the 
[fine-tuned T5GEC](https://github.com/zhangying9128/BTR?tab=readme-ov-file#pre-training-the-btr-with-realnewslike-dataset).

**Comment by antct** [comment]
Sorry for missing the file. Thanks~

**Comment by zhangying9128** [comment]
You are welcome. By the way, when you use T5GEC, remember to use the original transformer from huggingface, you can follow the github of cLang8 to use it.
